on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.19.2
      env:
        PAGES_BRANCH: gh-pages
        TOKEN: ${{ secrets.TOKEN }}
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

    - name: Deploy to GitHub Pages 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: main
        folder: '.'
        